"""Shared summary storage with Qwen and Gemini generation policies."""

from __future__ import annotations

from contextlib import contextmanager, ExitStack
from dataclasses import replace
from pathlib import Path
from typing import Callable, Iterator
from tqdm import tqdm
from extraction.progress import InferenceProgress
from extraction.qwen_runtime import QwenRuntime

from artifact_io import atomic_write_json
from extraction.backends.qwen_workers import QwenGenerationTask, QwenWorkerPool
from extraction.descriptions import description_summary_prompt
from extraction.errors import ExtractionStepError
from extraction.input_tracking import clear_dirty
from extraction.recovery import fingerprint, penalty_schedule
from extraction.failures import FailureLog
from extraction.generation import generate_once
from extraction.scene_storage import read_scene_records
from extraction.semantic_graph import graph_summary_prompt
from extraction.step_support import minimal_description_records, minimal_graph_records, result
from extraction.summary_validation import SUMMARY_SCHEMA_VERSION, inspect_summary
from pipeline_runtime import read_json, read_jsonl

GenerationFunction = Callable


def reuse_summary_document(
    output_path, *, schema_version=SUMMARY_SCHEMA_VERSION, content_id, arm, scene_count=None
):
    try:
        doc = read_json(output_path)
        if (
            doc.get("schema_version") != schema_version
            or doc.get("content_id") != content_id
            or doc.get("arm") != arm
            or type(doc.get("scene_count")) is not int
            or doc["scene_count"] <= 0
            or scene_count is not None
            and doc["scene_count"] != scene_count
            or doc.get("status") not in {"complete", "raw_fallback"}
            or not isinstance(doc.get("provenance"), dict)
        ):
            raise ValueError("summary identity, provenance, status, or scene count mismatch")
        text, violations = inspect_summary(doc.get("text"))
        if not text or doc.get("word_count") != len(text.split()):
            raise ValueError("empty summary or incorrect word count")
        if doc["status"] == "complete" and (violations or doc.get("violations") != []):
            raise ValueError("normal summary violates the summary contract")
        if doc["status"] == "raw_fallback" and not isinstance(doc.get("violations"), list):
            raise ValueError("raw summary requires recorded violations")
        return doc
    except (ValueError, KeyError, TypeError) as exc:
        raise ExtractionStepError(f"invalid summary {output_path}: {exc}") from exc


def summary_model_from_document(doc):
    """Recognize older Qwen/Gemini provenance without a summary_model field."""
    provenance = doc.get("provenance", {})
    if not isinstance(provenance, dict):
        return "qwen"
    explicit = provenance.get("summary_model")
    if explicit is not None:
        return explicit
    model = provenance.get("model", {})
    settings = provenance.get("settings")
    if (isinstance(settings, dict) and settings.get("backend") == "gemini") or (
        isinstance(model, dict) and "model_id" in model
    ):
        return "gemini"
    return "qwen"


def summary_failure_rows(directory):
    """Read failures without invoking FailureLog's migration side effects."""
    paths = [directory / "failure.jsonl", *sorted((directory / "failures").glob("*.jsonl")),
             directory / "failures.jsonl"]
    rows = {}
    for path in paths:
        if path.is_file():
            for row in read_jsonl(path):
                rows[str(row.get("content_id", path.stem))] = row
    return rows


def check_summary_model(directory, model):
    for path in directory.glob("*.json"):
        try:
            doc = read_json(path)
        except ValueError:
            continue  # Invalid documents are regenerated by the normal input pass.
        if not isinstance(doc, dict) or "provenance" not in doc:
            continue
        if summary_model_from_document(doc) != model:
            raise ExtractionStepError(
                f"summary model mismatch in {path}; use --force or a new run"
            )
    for row in summary_failure_rows(directory).values():
        if row.get("summary_model", "qwen") != model:
            raise ExtractionStepError(
                f"summary failure model mismatch in {directory}; use --force or a new run"
            )


def run_summary_stage(
    context,
    *,
    arm,
    schema,
    catalog,
    metadata_titles,
    provenance,
    generation,
    model,
    gemini_pool_factory,
    force=False,
    generator_factory,
):
    titles = {}
    for row in metadata_titles:
        cid = str(row["content_id"])
        if cid in titles or not isinstance(row.get("title"), str):
            raise ExtractionStepError(f"invalid metadata title for {cid}")
        titles[cid] = row["title"].strip()
    if set(titles) != {str(item["content_id"]) for item in catalog}:
        raise ExtractionStepError("metadata titles do not match catalog")
    output_dir = context.summary_dir(arm.representation, arm.model, model)
    scene_dir = context.extraction_dir(arm.representation, arm.model, "scenes")
    if not force:
        check_summary_model(output_dir, model)
    failures = FailureLog(output_dir)
    content_ids = [str(item["content_id"]) for item in catalog]
    if force:
        # Reset only the selected summary model before sending new requests.
        for path in output_dir.glob("*.json"):
            path.unlink()
            clear_dirty(path)
        failures.clear_contents(list(failures.by_content))
    template = schema.read_text(encoding="utf-8")
    graph = arm.representation == "graph"
    normalize = minimal_graph_records if graph else minimal_description_records
    build_prompt = graph_summary_prompt if graph else description_summary_prompt
    settings = context.config["extraction"]
    max_tokens = settings["graph" if graph else "description"]["summary_max_new_tokens"]
    schedule = penalty_schedule(settings["summary_repetition_penalty"]) if model == "qwen" else [1.0]
    if any(left >= right for left, right in zip(schedule, schedule[1:])):
        raise ExtractionStepError("summary repetition penalties must be strictly increasing")
    pending, documents, next_penalties = {}, {}, {}

    def publish(cid, text, violations, *, raw=False):
        records, prov, _ = pending[cid]
        if not text.strip():
            text = build_prompt("{scenes}", records, english_title=titles[cid])
            prov = {**prov, "summary_fallback": "scene_observations"}
        doc = {
            "schema_version": SUMMARY_SCHEMA_VERSION,
            "content_id": cid,
            "arm": arm.name,
            "status": "raw_fallback" if raw else "complete",
            "text": text,
            "scene_count": len(records),
            "word_count": len(text.split()),
            "violations": violations,
            "correction_count": 0,
            "provenance": prov,
        }
        output = output_dir / f"{cid}.json"
        # Reopening a terminal failure should not rewrite its published artifact.
        try:
            unchanged = output.is_file() and read_json(output) == doc
        except (ValueError, OSError):
            unchanged = False
        if not unchanged:
            atomic_write_json(output, doc, durable=True)
        clear_dirty(output)
        documents[cid] = doc

    for item in catalog:
        cid = str(item["content_id"])
        source = scene_dir / f"{cid}.jsonl"
        output = output_dir / f"{cid}.json"
        if output.is_file() and not force and not failures.contains(cid, None):
            try:
                existing = reuse_summary_document(output, content_id=cid, arm=arm.name)
            except ExtractionStepError:
                pass
            else:
                clear_dirty(output)
                documents[cid] = existing
                continue
        if not source.is_file():
            raise ExtractionStepError(f"missing scene input: {source}")
        try:
            records = normalize(read_scene_records(source), source)
        except (ValueError, KeyError, TypeError) as exc:
            raise ExtractionStepError(f"invalid scene input {source}: {exc}") from exc
        if not records:
            raise ExtractionStepError(f"empty scene input: {source}")
        raw_count = sum(r.get("status") == "raw_fallback" for r in records)
        prov = {
            **provenance,
            "english_title": titles[cid],
            "scene_input_hash": fingerprint(records),
            "scene_path": str(source),
            "normal_scene_count": len(records) - raw_count,
            "raw_scene_count": raw_count,
        }
        prov["input_hash"] = fingerprint(prov)
        task = QwenGenerationTask(
            task_id=cid,
            image_paths=(),
            prompt=build_prompt(template, records, english_title=titles[cid]),
            max_new_tokens=max_tokens,
            **generation,
        )
        pending[cid] = (records, prov, task)
        failed = failures.rows.get((cid, None))
        if failed is None or model == "gemini":
            next_penalties[cid] = schedule[0]
        else:
            last = failed.get("repetition_penalty")
            if last is not None and (type(last) not in (int, float)
                                     or not 1 <= last <= 2):
                raise ExtractionStepError(f"invalid summary repetition_penalty for {cid}: {last}")
            next_penalty = next((value for value in schedule if last is not None and value > last), None)
            if next_penalty is None:
                publish(cid, failed["raw_output"], failed["error"].split(", "), raw=True)
            else:
                next_penalties[cid] = next_penalty

    runtime = QwenRuntime()
    with ExitStack() as resources:
        progress = resources.enter_context(InferenceProgress(
            total=len(next_penalties), reused=len(documents), empty=failures.count(content_ids),
            desc=f"Summary {arm.name} ({model})", unit="summary", progress_factory=tqdm,
        ))

        def receive(cid, text):
            normalized, violations = inspect_summary(text)
            event = runtime.current_result or {}
            if event.get("finish_reason") == "length":
                violations.append("max_tokens")
            final = penalty == schedule[-1]
            if violations:
                # Persist the completed attempt before publishing its terminal artifact.
                failures.record(cid, None, ", ".join(violations), text,
                                repetition_penalty=penalty, summary_model=model)
                if final:
                    publish(cid, text, violations, raw=True)
                    del next_penalties[cid]
                else:
                    (output_dir / f"{cid}.json").unlink(missing_ok=True)
                    next_penalties[cid] = schedule[schedule.index(penalty) + 1]
            else:
                publish(cid, normalized, [])
                failures.remove(cid, None)
                del next_penalties[cid]
            progress.complete(task_id=cid, failed=bool(violations),
                              raw=bool(final and violations))

        if next_penalties and model == "gemini":
            pool = gemini_pool_factory(settings["gemini"]["threads"],
                                       **context.config["models"]["gemini"])
            expected = set(next_penalties)
            completed = set()

            def receive_gemini(outcome):
                cid = outcome.task_id
                if cid not in expected or cid in completed:
                    raise ExtractionStepError(f"unexpected Gemini summary result: {cid}")
                normalized, violations = inspect_summary(outcome.text)
                if outcome.error:
                    violations.append(outcome.error)
                candidates = (outcome.response_diagnostics or {}).get("candidates") or []
                if any(str(getattr(c.get("finish_reason"), "value", c.get("finish_reason")))
                       .rsplit(".", 1)[-1].upper() == "MAX_TOKENS" for c in candidates):
                    violations.append("max_tokens")
                if violations:
                    failures.record(cid, None, ", ".join(violations), outcome.text,
                                    summary_model=model)
                    (output_dir / f"{cid}.json").unlink(missing_ok=True)
                else:
                    publish(cid, normalized, [])
                    failures.remove(cid, None)
                completed.add(cid)
                progress.complete(task_id=cid, failed=bool(violations), raw=False)

            pool.generate((pending[cid][2] for cid in next_penalties), receive_gemini,
                          on_progress=progress.update_stats)
            if completed != expected:
                raise ExtractionStepError("Gemini workers did not complete all summaries")
        elif next_penalties:
            generate = resources.enter_context(generator_factory(
                model_path=context.path("models", "qwen"), settings=settings.get("qwen"),
                image_limit=settings["visual_evidence"]["num_keyframes"], runtime=runtime,
                on_progress=progress.update_stats, log=progress.write_log,
            ))
            for index, penalty in enumerate(schedule, start=1):
                tasks = [replace(pending[cid][2], repetition_penalty=penalty)
                         for cid, value in next_penalties.items() if value == penalty]
                if tasks:
                    progress.begin_pass(len(tasks), index=index, count=len(schedule))
                    progress.write_log(f"[Qwen] repetition_penalty={penalty:.2f} "
                                       f"pass={index}/{len(schedule)} tasks={len(tasks)}")
                    generate_once(generate, tasks, receive)
    failed_count = failures.count(content_ids)
    print(f"[SUMMARY] {arm.name}: outputs={len(documents)} failed={failed_count}", flush=True)
    if model == "gemini" and failed_count:
        raise ExtractionStepError(f"{failed_count} Gemini summaries failed; rerun to retry")
    return result(f"summarize-{arm.name}", content_count=len(documents), failure_count=failed_count)


def qwen_progress(progress, stats):
    progress.update_stats(stats)


@contextmanager
def qwen_generator(
    *,
    model_path: Path,
    settings=None,
    image_limit=6,
    runtime=None,
    log=None,
    on_progress=None,
) -> Iterator[GenerationFunction]:
    def ready(event):
        if runtime:
            runtime.engine_ready(event)
        if log:
            log(
                f"[Qwen] GPU {event['gpu_id']} ready | {event['gpu_name']} | "
                f"settings={event['settings']}"
            )

    with ExitStack() as resources:
        pool = None

        def generate(tasks, on_task_complete=None):
            nonlocal pool
            if pool is None:
                if log:
                    log("[Qwen] starting vLLM GPU workers")
                pool = resources.enter_context(
                    QwenWorkerPool(
                        str(model_path),
                        settings=settings,
                        image_limit=image_limit,
                        on_runtime=ready,
                        on_progress=on_progress,
                    )
                )

            def complete(task_id, text):
                if runtime:
                    runtime.current_result = pool.last_result
                try:
                    on_task_complete(task_id, text)
                finally:
                    if runtime:
                        runtime.current_result = None

            return pool.generate(tasks, complete if on_task_complete else None)

        yield generate
